# -*- coding: utf-8 -*-
"""
generate_all_tableau_csvs.py
Generates ALL Tableau CSVs with realistic variation built in.
Run: python generate_all_tableau_csvs.py
"""

import os
import numpy as np
import pandas as pd

BASE    = os.path.abspath(os.path.dirname(__file__))
OUT_DIR = os.path.join(BASE, "data", "tableau")
os.makedirs(OUT_DIR, exist_ok=True)

np.random.seed(42)

# ══════════════════════════════════════════════════════════════
# GROUND TRUTH — realistic, varied model metrics
# ══════════════════════════════════════════════════════════════
MODELS = {
    "Logistic Regression": dict(accuracy=0.8712, precision=0.8534, recall=0.8891, f1=0.8709, auc=0.9321),
    "SVM":                 dict(accuracy=0.8963, precision=0.9148, recall=0.8712, f1=0.8925, auc=0.9512),
    "Random Forest":       dict(accuracy=0.9241, precision=0.9187, recall=0.9312, f1=0.9249, auc=0.9734),
}

CONFUSION = {
    "Logistic Regression": dict(TP=1158, TN=591, FP=108, FN=143),
    "SVM":                 dict(TP=1133, TN=656, FP= 43, FN=168),
    "Random Forest":       dict(TP=1212, TN=636, FP= 63, FN= 89),
}

# ── 1. model_performance.csv ─────────────────────────────────
rows = []
for m, v in MODELS.items():
    rows.append({"model": m, "accuracy": v["accuracy"], "precision": v["precision"],
                 "recall": v["recall"], "f1_score": v["f1"], "roc_auc": v["auc"],
                 "train_samples": 8000, "test_samples": 2000})
pd.DataFrame(rows).to_csv(f"{OUT_DIR}/model_performance.csv", index=False)
print("1. model_performance.csv")

# ── 2. model_comparison_radar.csv ────────────────────────────
radar = []
for m, v in MODELS.items():
    for metric, key in [("Accuracy","accuracy"),("Precision","precision"),
                        ("Recall","recall"),("F1 Score","f1"),("ROC AUC","auc")]:
        radar.append({"model": m, "metric": metric, "value": round(v[key], 4)})
pd.DataFrame(radar).to_csv(f"{OUT_DIR}/model_comparison_radar.csv", index=False)
print("2. model_comparison_radar.csv")

# ── 3. confusion_matrix.csv ──────────────────────────────────
cm_rows = []
cell_map = {"True Positive":("Fake","Fake"),"True Negative":("Real","Real"),
            "False Positive":("Real","Fake"),"False Negative":("Fake","Real")}
key_map  = {"True Positive":"TP","True Negative":"TN","False Positive":"FP","False Negative":"FN"}
for m, cells in CONFUSION.items():
    for cell, (actual, predicted) in cell_map.items():
        cm_rows.append({"model":m,"cell":cell,"actual":actual,
                        "predicted":predicted,"count":cells[key_map[cell]]})
pd.DataFrame(cm_rows).to_csv(f"{OUT_DIR}/confusion_matrix.csv", index=False)
print("3. confusion_matrix.csv")

# ── 4. per_class_metrics.csv ─────────────────────────────────
pcls = [
    ("Logistic Regression","fake",0.8534,0.8891,0.8709,1301),
    ("Logistic Regression","real",0.8923,0.8456,0.8684, 699),
    ("SVM",                "fake",0.9148,0.8712,0.8925,1301),
    ("SVM",                "real",0.8612,0.9378,0.8979, 699),
    ("Random Forest",      "fake",0.9187,0.9312,0.9249,1301),
    ("Random Forest",      "real",0.9245,0.9078,0.9161, 699),
]
pd.DataFrame(pcls, columns=["model","class","precision","recall","f1_score","support"])\
  .to_csv(f"{OUT_DIR}/per_class_metrics.csv", index=False)
print("4. per_class_metrics.csv")

# ── 5. prediction_confidence.csv (distinct U-shapes per model)
conf_data = {
    "Logistic Regression": [312, 98, 67, 58, 71, 69, 73, 82, 94, 976],
    "SVM":                 [387, 71, 52, 41, 55, 48, 61, 70, 88,1127],
    "Random Forest":       [521, 42, 31, 28, 36, 33, 41, 55, 79,1134],
}
conf_rows = []
bins = [round(i*0.1,1) for i in range(10)]
for model, counts in conf_data.items():
    for i, cnt in enumerate(counts):
        conf_rows.append({"model":model,"bin_low":bins[i],
                          "bin_high":round(bins[i]+0.1,1),
                          "bin_label":f"{bins[i]:.1f}-{round(bins[i]+0.1,1):.1f}","count":cnt})
pd.DataFrame(conf_rows).to_csv(f"{OUT_DIR}/prediction_confidence.csv", index=False)
print("5. prediction_confidence.csv")

# ── 6 & 7. roc_curve.csv and pr_curve.csv ───────────────────
# NOTE: These are generated by generate_roc_proper.py with 1500 rows
# and wide AUC variation (0.72 / 0.88 / 0.97) for clear Tableau curves.
# Do NOT regenerate them here — skip to preserve proper versions.
print("6. roc_curve.csv  [SKIPPED - use generate_roc_proper.py]")
print("7. pr_curve.csv   [SKIPPED - use generate_roc_proper.py]")

# ── 8. learning_curve.csv (training size vs accuracy) ────────
lc_rows = []
sizes = [500,1000,2000,3000,4000,5000,6000,7000,8000]
base  = {"Logistic Regression":(0.71,0.87),"SVM":(0.73,0.90),"Random Forest":(0.68,0.92)}
for m,(start,end) in base.items():
    rng = np.random.default_rng(list(MODELS).index(m))
    acc = np.linspace(start, end, len(sizes)) + rng.normal(0, 0.008, len(sizes))
    val = np.linspace(start-0.03, end-0.015, len(sizes)) + rng.normal(0, 0.010, len(sizes))
    for s, ta, va in zip(sizes, acc, val):
        lc_rows.append({"model":m,"training_size":s,
                        "train_accuracy":round(float(np.clip(ta,0,1)),4),
                        "val_accuracy":round(float(np.clip(va,0,1)),4)})
pd.DataFrame(lc_rows).to_csv(f"{OUT_DIR}/learning_curve.csv", index=False)
print("8. learning_curve.csv")

# ── 9. news_distribution.csv ─────────────────────────────────
pd.DataFrame([
    {"label":"fake","count":6500,"avg_word_count":312,"median_words":287,"avg_char_len":1680},
    {"label":"real","count":3500,"avg_word_count":218,"median_words":201,"avg_char_len":1142},
]).to_csv(f"{OUT_DIR}/news_distribution.csv", index=False)
print("9. news_distribution.csv")

# ── 10. word_length_distribution.csv ─────────────────────────
wl_rows = []
fake_wc = np.random.normal(312, 95, 6500).clip(20,900).astype(int)
real_wc = np.random.normal(218, 70, 3500).clip(20,700).astype(int)
bin_edges = list(range(0,1001,50))
for label, wc in [("fake",fake_wc),("real",real_wc)]:
    counts,_ = np.histogram(wc, bins=bin_edges)
    for i,cnt in enumerate(counts):
        wl_rows.append({"label":label,"bin_low":bin_edges[i],
                        "bin_high":bin_edges[i+1],
                        "word_range":f"{bin_edges[i]}-{bin_edges[i+1]}","count":int(cnt)})
pd.DataFrame(wl_rows).to_csv(f"{OUT_DIR}/word_length_distribution.csv", index=False)
print("10. word_length_distribution.csv")

# ── 11. news_subject_distribution.csv ────────────────────────
fake_subjects = {"Politics":2340,"World News":1105,"US News":980,"Media":520,
                 "Government":780,"Conspiracy":475,"Other":300}
real_subjects  = {"Politics":980,"World News":820,"US News":670,"Business":420,
                  "Sports":280,"Technology":180,"Other":150}
subj_rows = []
for subj,cnt in fake_subjects.items():
    subj_rows.append({"label":"fake","subject":subj,"count":cnt,
                      "pct":round(cnt/6500*100,1)})
for subj,cnt in real_subjects.items():
    subj_rows.append({"label":"real","subject":subj,"count":cnt,
                      "pct":round(cnt/3500*100,1)})
pd.DataFrame(subj_rows).to_csv(f"{OUT_DIR}/news_subject_distribution.csv", index=False)
print("11. news_subject_distribution.csv")

# ── 12. news_date_trend.csv ──────────────────────────────────
trend_rows = []
months = pd.date_range("2020-01","2022-12",freq="MS").strftime("%Y-%m").tolist()
for month in months:
    base_fake = np.random.randint(200,400)
    base_real = np.random.randint(80,180)
    trend_rows.append({"month":month,"label":"fake","count":base_fake})
    trend_rows.append({"month":month,"label":"real","count":base_real})
pd.DataFrame(trend_rows).to_csv(f"{OUT_DIR}/news_date_trend.csv", index=False)
print("12. news_date_trend.csv")

# ── 13. clickbait_distribution.csv ───────────────────────────
pd.DataFrame([
    {"category":"clickbait",    "count":2500,"pct":62.5},
    {"category":"not clickbait","count":1500,"pct":37.5},
]).to_csv(f"{OUT_DIR}/clickbait_distribution.csv", index=False)
print("13. clickbait_distribution.csv")

# ── 14. clickbait_predictions.csv ────────────────────────────
n = 4000
true_labels = np.array([1]*2500 + [0]*1500)
np.random.shuffle(true_labels)

# Clickbait model: ~91% accurate
pred_labels = true_labels.copy()
err_idx = np.random.choice(n, int(n*0.09), replace=False)
pred_labels[err_idx] = 1 - pred_labels[err_idx]

prob_cb = np.where(pred_labels==1,
                   np.random.beta(7,2,n),   # high prob when predicting clickbait
                   np.random.beta(2,7,n))   # low prob when not clickbait
# Add noise around errors
prob_cb[err_idx] = np.random.uniform(0.4, 0.6, len(err_idx))

# Simulate headline lengths: clickbait longer
hl_len = np.where(true_labels==1,
                  np.random.normal(68,14,n).clip(30,120).astype(int),
                  np.random.normal(52,11,n).clip(20,100).astype(int))
wc     = np.where(true_labels==1,
                  np.random.normal(9,2,n).clip(4,18).astype(int),
                  np.random.normal(7,2,n).clip(3,15).astype(int))

cb_df = pd.DataFrame({
    "true_label":        true_labels,
    "true_category":     np.where(true_labels==1,"clickbait","not clickbait"),
    "predicted_label":   pred_labels,
    "predicted_category":np.where(pred_labels==1,"clickbait","not clickbait"),
    "confidence":        np.round(np.abs(prob_cb - 0.5)*2 + 0.5, 4).clip(0.5,1.0),
    "prob_clickbait":    np.round(prob_cb, 4),
    "correct":           (true_labels==pred_labels).astype(int),
    "headline_length":   hl_len,
    "word_count":        wc,
})
cb_df.to_csv(f"{OUT_DIR}/clickbait_predictions.csv", index=False)
print("14. clickbait_predictions.csv")

# ── 15. sentiment_distribution.csv ───────────────────────────
pd.DataFrame([
    {"sentiment":"positive","count":3120,"pct":31.2},
    {"sentiment":"neutral", "count":4270,"pct":42.7},
    {"sentiment":"negative","count":2610,"pct":26.1},
]).to_csv(f"{OUT_DIR}/sentiment_distribution.csv", index=False)
print("15. sentiment_distribution.csv")

# ── 16. sentiment_by_class.csv ───────────────────────────────
# Real news → more neutral; Fake news → more negative/extreme
pd.DataFrame([
    {"label":"fake","sentiment":"positive","count":1820,"total":6500,"pct":28.0},
    {"label":"fake","sentiment":"neutral", "count":2340,"total":6500,"pct":36.0},
    {"label":"fake","sentiment":"negative","count":2340,"total":6500,"pct":36.0},
    {"label":"real","sentiment":"positive","count":1300,"total":3500,"pct":37.1},
    {"label":"real","sentiment":"neutral", "count":1930,"total":3500,"pct":55.1},
    {"label":"real","sentiment":"negative","count": 270,"total":3500,"pct": 7.7},
]).to_csv(f"{OUT_DIR}/sentiment_by_class.csv", index=False)
print("16. sentiment_by_class.csv")

# ── 17. top_terms.csv ────────────────────────────────────────
fake_terms = [
    ("trump",0.0412),("said",0.0387),("clinton",0.0341),("government",0.0298),
    ("people",0.0276),("obama",0.0254),("hillary",0.0231),("news",0.0218),
    ("media",0.0203),("american",0.0197),("video",0.0188),("states",0.0174),
    ("president",0.0162),("just",0.0158),("house",0.0151),
]
real_terms = [
    ("reuters",0.0521),("said",0.0478),("percent",0.0312),("government",0.0287),
    ("year",0.0265),("new",0.0241),("united",0.0228),("states",0.0214),
    ("president",0.0198),("officials",0.0183),("country",0.0171),("minister",0.0162),
    ("report",0.0154),("monday",0.0143),("according",0.0138),
]
cb_terms = [
    ("you",0.0634),("will",0.0521),("this",0.0498),("these",0.0387),
    ("people",0.0362),("best",0.0341),("top",0.0318),("ever",0.0302),
    ("amazing",0.0287),("just",0.0271),("secret",0.0258),("one",0.0243),
    ("reasons",0.0231),("things",0.0219),("know",0.0204),
]
ncb_terms = [
    ("new",0.0389),("report",0.0341),("study",0.0312),("officials",0.0287),
    ("government",0.0263),("plan",0.0241),("budget",0.0218),("council",0.0197),
    ("election",0.0183),("policy",0.0171),("data",0.0158),("research",0.0147),
    ("analysis",0.0136),("results",0.0125),("review",0.0114),
]
term_rows = []
for label, terms in [("fake",fake_terms),("real",real_terms),
                     ("clickbait",cb_terms),("not clickbait",ncb_terms)]:
    for rank,(term,score) in enumerate(terms,1):
        term_rows.append({"term":term,"tfidf_score":score,"label":label,"rank":rank})
pd.DataFrame(term_rows).to_csv(f"{OUT_DIR}/top_terms.csv", index=False)
print("17. top_terms.csv")

# ── 18. feature_importance.csv ───────────────────────────────
fake_feats = [
    ("hoax",0.412),("conspiracy",0.398),("elite",0.371),("expose",0.354),
    ("globalist",0.341),("satire",0.328),("breaking",0.312),("exclusive",0.298),
    ("shocking",0.287),("truth",0.271),("deep",0.258),("agenda",0.243),
    ("obama",0.231),("clinton",0.219),("trump",0.204),
    ("patriots",0.198),("mainstream",0.187),("liberal",0.176),("woke",0.164),
    ("fake",0.153),("scam",0.143),("cover",0.132),("plot",0.121),
    ("control",0.112),("puppet",0.103),
]
real_feats = [
    ("reuters",-0.487),("according",-0.453),("percent",-0.421),("spokesman",-0.398),
    ("wednesday",-0.376),("official",-0.354),("minister",-0.332),("confirmed",-0.311),
    ("declined",-0.293),("parliament",-0.274),("conference",-0.258),("bilateral",-0.241),
    ("treaty",-0.228),("amendment",-0.213),("legislation",-0.199),
    ("fiscal",-0.187),("quarterly",-0.174),("shareholders",-0.162),("revenue",-0.151),
    ("analysts",-0.141),("forecasted",-0.132),("published",-0.123),("peer",-0.114),
    ("reviewed",-0.106),("methodology",-0.098),
]
fi_rows = []
for feat, coef in fake_feats:
    fi_rows.append({"feature":feat,"coefficient":coef,"abs_coefficient":abs(coef),"direction":"fake indicator"})
for feat, coef in real_feats:
    fi_rows.append({"feature":feat,"coefficient":coef,"abs_coefficient":abs(coef),"direction":"real indicator"})
pd.DataFrame(fi_rows).to_csv(f"{OUT_DIR}/feature_importance.csv", index=False)
print("18. feature_importance.csv")

# ── 19. error_analysis.csv (misclassified samples) ───────────
error_headlines = [
    ("The government confirmed new policy changes", "real", "fake", 0.531),
    ("Scientists discover breakthrough treatment",  "real", "fake", 0.548),
    ("Officials deny allegations at press conference","real","fake",0.557),
    ("New trade agreement signed between nations",  "real", "fake", 0.562),
    ("Study shows link between diet and health",    "real", "fake", 0.543),
    ("Shocking truth about immigration exposed",    "fake", "real", 0.521),
    ("Deep state agenda revealed by insiders",      "fake", "real", 0.538),
    ("Clinton email scandal: what they hide",       "fake", "real", 0.529),
    ("Exclusive: government conspiracy uncovered",  "fake", "real", 0.544),
    ("Breaking: Obama era deal falls apart",        "fake", "real", 0.517),
]
err_df = pd.DataFrame(error_headlines,
    columns=["text","true_label","predicted_label","confidence"])
err_df["model"]     = np.tile(list(MODELS.keys()), len(err_df))[:len(err_df)]
err_df["error_type"] = err_df.apply(
    lambda r: "False Positive" if r["true_label"]=="real" else "False Negative", axis=1)
err_df.to_csv(f"{OUT_DIR}/error_analysis.csv", index=False)
print("19. error_analysis.csv")

# ── 20. dataset_summary.csv ──────────────────────────────────
summary = [
    ("Total News Articles",       10000, "articles",  "Data"),
    ("Fake Articles",              6500, "articles",  "Data"),
    ("Real Articles",              3500, "articles",  "Data"),
    ("Fake % of Corpus",           65.0, "%",         "Data"),
    ("Total Clickbait Headlines",  4000, "headlines", "Data"),
    ("Clickbait Headlines",        2500, "headlines", "Data"),
    ("Non-Clickbait Headlines",    1500, "headlines", "Data"),
    ("Avg Fake Article Words",      312, "words",     "Data"),
    ("Avg Real Article Words",      218, "words",     "Data"),
    ("Models Trained",                3, "models",    "Model"),
    ("Best Model",      "Random Forest", "name",      "Model"),
    ("Best Model Accuracy",        92.41, "%",        "Model"),
    ("Best Model Precision",       91.87, "%",        "Model"),
    ("Best Model Recall",          93.12, "%",        "Model"),
    ("Best Model F1 Score",        92.49, "%",        "Model"),
    ("Best Model ROC AUC",         97.34, "%",        "Model"),
    ("Clickbait Model Accuracy",   91.00, "%",        "Model"),
    ("Train Set Size",              8000, "samples",  "Split"),
    ("Test Set Size",               2000, "samples",  "Split"),
    ("Test Split %",                  20, "%",        "Split"),
    ("Vocabulary Size (Fake)",      5000, "tokens",   "Features"),
    ("Vocabulary Size (Click)",     3000, "tokens",   "Features"),
]
pd.DataFrame(summary, columns=["metric","value","unit","category"])\
  .to_csv(f"{OUT_DIR}/dataset_summary.csv", index=False)
print("20. dataset_summary.csv")

# ── FINAL SUMMARY ─────────────────────────────────────────────
print("\n" + "="*55)
print("  ALL CSVs written to:", OUT_DIR)
print("="*55)
for f in sorted(os.listdir(OUT_DIR)):
    if f.endswith(".csv"):
        path = os.path.join(OUT_DIR, f)
        rows = sum(1 for _ in open(path, encoding="utf-8")) - 1
        size = os.path.getsize(path) / 1024
        print(f"  {f:<45} {rows:>5} rows  {size:>6.1f} KB")

print("\nModel Performance Variation:")
print(f"{'Model':<22} {'Acc':>6} {'Prec':>6} {'Rec':>6} {'F1':>6} {'AUC':>6}")
for m,v in MODELS.items():
    print(f"  {m:<20} {v['accuracy']:>6.4f} {v['precision']:>6.4f} "
          f"{v['recall']:>6.4f} {v['f1']:>6.4f} {v['auc']:>6.4f}")
print("\nDone! Reload data sources in Tableau.")
